url: "" # the base hostname & protocol for your site, e.g. http://example.com
baseurl: "" # the subpath of your site, e.g. /blog
title: "Emmanuel Orozco | Software Engineer | Musician" # the name of your site, e.g. ACME Corp.

permalink: /:slugified_categories/:title